root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/web"
bin = "tmp/main"
full_bin = "tmp/main"
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
